# Site settings
title: Teddie Mae
email: f/xoqbqljb
url: https://github.com/teddiemae/teddiemae.com
description: "Teddie Mae Birmingham Realty"
keywords: "Birmingham, Birmingham Alabama, Birmingham AL, Birmingham Real Estate, Birmingham AL Real Estate, Birmingham Alabama Real Estate"
skills: "Your <i>personal</i> Birmingham real estate agent."
meta_author: Mae Teddie


# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
#
# fce59c # Yellow
# bfe4f0 # Blue
# c77890 # Light Pink
# 7e246b # Purple
# beeac0 # Light Green
color:
  primary: 7e246b # Purple
  primary-rgb: "126,36,107"
  secondary: c77890 # Light Pink
  secondary-dark: beeac0 # Light Green

# Footer settings
footer:
  copyright: Teddie Mae
  location: Birmingham
  social: 
  credits: 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
